spring.application.name=MicroservicesProjectServiceRegistery
server.port=8084
eureka.instance.hostname=localhost

# Now this  lines helps to reduce the chance  of this eureka server to make client itself
 eureka.client.register-with-eureka=false
 eureka.client.fetch-registry=false
# Add this to your Eureka SERVER configuration
eureka.server.enable-self-preservation=false